// <auto-generated />
namespace shopping_basket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductImages));
        
        string IMigrationMetadata.Id
        {
            get { return "202012291926399_ProductImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
